import { Film } from "../models/film.model";

export const FILMS: Film[] = [
  {
    id: 0,
    title: 'Марсианин 1',
    original: 'The Martian 2015',
    category: 'Фантастика, приключения',
    img: './images/film.png',
    link: './film.html',
    rating: 7.8,
  },
  {
    id: 1,
    title: 'Марсианин 2',
    original: 'The Martian 2015',
    category: 'Фантастика, приключения',
    img: './images/film.png',
    link: './film.html',
    rating: 7.8,
  },
  {
    id: 2,
    title: 'Марсианин 3',
    original: 'The Martian 2015',
    category: 'Фантастика, приключения',
    img: './images/film.png',
    link: './film.html',
    rating: 7.8,
  },
  {
    id: 3,
    title: 'Марсианин 4',
    original: 'The Martian 2015',
    category: 'Фантастика, приключения',
    img: './images/film.png',
    link: './film.html',
    rating: 7.8,
  },
  {
    id: 4,
    title: 'Марсианин 5',
    original: 'The Martian 2015',
    category: 'Фантастика, приключения',
    img: './images/film.png',
    link: './film.html',
    rating: 7.8,
  },
  {
    id: 5,
    title: 'Марсианин 6',
    original: 'The Martian 2015',
    category: 'Фантастика, приключения',
    img: './images/film.png',
    link: './film.html',
    rating: 7.8,
  },
];
